# Generated by Django 2.0.3 on 2018-03-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_images', models.FileField(default='', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Livebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Liveboxes',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('src_type', models.IntegerField(default=0)),
                ('src_path', models.CharField(max_length=50)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Item')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.AddField(
            model_name='livebox',
            name='box_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Owner'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Livebox'),
        ),
    ]
