# Generated by Django 2.0.3 on 2018-03-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.ImageField(default='', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_images',
        ),
        migrations.RemoveField(
            model_name='story',
            name='src_path',
        ),
        migrations.RemoveField(
            model_name='story',
            name='src_type',
        ),
        migrations.AddField(
            model_name='livebox',
            name='bluetooth_device',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='audio_path',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='video_path',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Item'),
        ),
    ]
